version: 2.1

jobs:
  checkout_code:
    working_directory: ~/circleci-nx
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-nx
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - run: ls
      - run: yarn nx build --no-cache
      - run: ls
workflows:
  NX Workflow:
    jobs:
      - checkout_code
