version: 2.1
jobs:
  quality-gates:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Linting
          command: |
            yarn nx lint
      - run:
          name: Unit Tests
          command: |
            yarn nx test
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Building app
          command: |
            yarn nx build

workflows:
  NX Workflow:
    jobs:
      - quality-gates
      - build:
          requires:
            - quality-gates
