version: 2.1

jobs:
  install_dependencies:
    working_directory: ~/circleci-nx
    docker:
      - image: cimg/node:16.2-browsers
    steps:
      - checkout:
          path: ~/circleci-nx
      - run: node --version
      - run: pwd
      - run: cd ../
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Linting
          command: |
<<<<<<< HEAD
            yarn nx lint

workflows:
  NX Workflow:
    jobs:
      - install_dependencies
=======
            yarn nx lint
>>>>>>> 65caa2d99af48b299cb5aef407f4059c95b932a7
