version: 2.1

jobs:
  install_dependencies:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.2-browsers
    steps:
      - checkout
      - run: node --version
      - run: pwd
      - run: cd ../
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  quality-gates:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.2-browsers
    steps:
      - run:
          name: Linting
          command: |
            yarn nx lint
      - run:
          name: Unit Tests
          command: |
            yarn nx test
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.2-browsers
    steps:
      - run:
          name: Building app
          command: |
            yarn nx build

workflows:
  NX Workflow:
    jobs:
      - install_dependencies
      - quality-gates:
          requires:
            - install_dependencies
      - build:
          requires:
            - install_dependencies
            - quality-gates
