version: 2.1

jobs:
  checkout_code:
    working_directory: ~/circleci-nx
    docker:
      - image: cimg/node:16.2-browsers
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/circleci-nx
  install_dependencies:
    working_directory: ~/circleci-nx
    docker:
      - image: cimg/node:16.2-browsers
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: pwd
      - run: ls
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  quality-gates:
    working_directory: ~/circleci-nx
    docker:
      - image: cimg/node:16.2-browsers
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: pwd
      - run: ls

workflows:
  NX Workflow:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - quality-gates:
          requires:
            - install_dependencies
